### ISSUE TITLE
The plugin will randomly fail to export something

### ISSUE THREAD

**Issue by HR-administrative** [timbze/UCRM-plugins#2]
of any category. Plugin used to be unusable but after switching DNS from BTL to Google it only fails with about four out of a thousand entries. And if failed once, it will never retry exporting that item; I suggest instead of trying to make it flawless, maybe program it to retry twice and then give up.

**Comment by timbze** [comment]
Should be quite a bit improved by 
d7eac76f
3e12a16e
b6788856

**Comment by timbze** [comment]
Should be mostly fixed now after fce403b9
